use crate::element::Element;
use crate::element::ElementSymbol;

pub const ELEMENT_TABLE: [Element; 103] = [
    Element {
        symbol: ElementSymbol::H,
        atomic_number: 0_u8,
        lcao: 1_u8,
        mass: 1.0080000162,
        potential: "H_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(0.32),
    },
    Element {
        symbol: ElementSymbol::He,
        atomic_number: 2_u8,
        lcao: 1_u8,
        mass: 4.0029997826,
        potential: "He_00.usp",
        spin: 0_u8,
        covalent_radius: Some(0.46),
    },
    Element {
        symbol: ElementSymbol::Li,
        atomic_number: 3_u8,
        lcao: 2_u8,
        mass: 6.9400000572,
        potential: "Li_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.33),
    },
    Element {
        symbol: ElementSymbol::Be,
        atomic_number: 4_u8,
        lcao: 2_u8,
        mass: 9.0120000839,
        potential: "Be_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.02),
    },
    Element {
        symbol: ElementSymbol::B,
        atomic_number: 5_u8,
        lcao: 2_u8,
        mass: 10.8100004196,
        potential: "B_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(0.85),
    },
    Element {
        symbol: ElementSymbol::C,
        atomic_number: 6_u8,
        lcao: 2_u8,
        mass: 12.0109996796,
        potential: "C_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(0.75),
    },
    Element {
        symbol: ElementSymbol::N,
        atomic_number: 7_u8,
        lcao: 2_u8,
        mass: 14.0069999695,
        potential: "N_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(0.71),
    },
    Element {
        symbol: ElementSymbol::O,
        atomic_number: 8_u8,
        lcao: 2_u8,
        mass: 15.9989995956,
        potential: "O_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(0.63),
    },
    Element {
        symbol: ElementSymbol::F,
        atomic_number: 9_u8,
        lcao: 2_u8,
        mass: 18.9979991913,
        potential: "F_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(0.64),
    },
    Element {
        symbol: ElementSymbol::Ne,
        atomic_number: 10_u8,
        lcao: 2_u8,
        mass: 20.1790008545,
        potential: "Ne_00.usp",
        spin: 0_u8,
        covalent_radius: Some(0.67),
    },
    Element {
        symbol: ElementSymbol::Na,
        atomic_number: 11_u8,
        lcao: 4_u8,
        mass: 22.9899997711,
        potential: "Na_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.55),
    },
    Element {
        symbol: ElementSymbol::Mg,
        atomic_number: 12_u8,
        lcao: 3_u8,
        mass: 24.3050003052,
        potential: "Mg_00PW91.usp",
        spin: 0_u8,
        covalent_radius: Some(1.39),
    },
    Element {
        symbol: ElementSymbol::Al,
        atomic_number: 13_u8,
        lcao: 2_u8,
        mass: 26.982000351,
        potential: "Al_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.26),
    },
    Element {
        symbol: ElementSymbol::Si,
        atomic_number: 14_u8,
        lcao: 2_u8,
        mass: 28.0849990845,
        potential: "Si_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.16),
    },
    Element {
        symbol: ElementSymbol::P,
        atomic_number: 15_u8,
        lcao: 2_u8,
        mass: 30.9740009308,
        potential: "P_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.11),
    },
    Element {
        symbol: ElementSymbol::S,
        atomic_number: 16_u8,
        lcao: 2_u8,
        mass: 32.0600013733,
        potential: "S_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.03),
    },
    Element {
        symbol: ElementSymbol::Cl,
        atomic_number: 17_u8,
        lcao: 2_u8,
        mass: 35.452999115,
        potential: "Cl_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(0.99),
    },
    Element {
        symbol: ElementSymbol::Ar,
        atomic_number: 18_u8,
        lcao: 2_u8,
        mass: 39.9480018616,
        potential: "Ar_00.usp",
        spin: 0_u8,
        covalent_radius: Some(0.96),
    },
    Element {
        symbol: ElementSymbol::K,
        atomic_number: 19_u8,
        lcao: 4_u8,
        mass: 39.0979995728,
        potential: "K_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.96),
    },
    Element {
        symbol: ElementSymbol::Ca,
        atomic_number: 20_u8,
        lcao: 4_u8,
        mass: 40.0800018311,
        potential: "Ca_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.71),
    },
    Element {
        symbol: ElementSymbol::Sc,
        atomic_number: 21_u8,
        lcao: 5_u8,
        mass: 44.9560012817,
        potential: "Sc_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.48),
    },
    Element {
        symbol: ElementSymbol::Ti,
        atomic_number: 22_u8,
        lcao: 5_u8,
        mass: 47.9000015259,
        potential: "Ti_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.36),
    },
    Element {
        symbol: ElementSymbol::V,
        atomic_number: 23_u8,
        lcao: 5_u8,
        mass: 50.9410018921,
        potential: "V_00PBE.usp",
        spin: 2_u8,
        covalent_radius: Some(1.34),
    },
    Element {
        symbol: ElementSymbol::Cr,
        atomic_number: 24_u8,
        lcao: 5_u8,
        mass: 51.9959983826,
        potential: "Cr_00PBE.usp",
        spin: 3_u8,
        covalent_radius: Some(1.22),
    },
    Element {
        symbol: ElementSymbol::Mn,
        atomic_number: 25_u8,
        lcao: 3_u8,
        mass: 54.9379997253,
        potential: "Mn_00PBE.uspcc",
        spin: 5_u8,
        covalent_radius: Some(1.19),
    },
    Element {
        symbol: ElementSymbol::Fe,
        atomic_number: 26_u8,
        lcao: 3_u8,
        mass: 55.8470001221,
        potential: "Fe_00PBE.uspcc",
        spin: 4_u8,
        covalent_radius: Some(1.16),
    },
    Element {
        symbol: ElementSymbol::Co,
        atomic_number: 27_u8,
        lcao: 3_u8,
        mass: 58.9329986572,
        potential: "Co_00PBE.uspcc",
        spin: 3_u8,
        covalent_radius: Some(1.11),
    },
    Element {
        symbol: ElementSymbol::Ni,
        atomic_number: 28_u8,
        lcao: 3_u8,
        mass: 58.7099990845,
        potential: "Ni_00PBE.uspcc",
        spin: 2_u8,
        covalent_radius: Some(1.1),
    },
    Element {
        symbol: ElementSymbol::Cu,
        atomic_number: 29_u8,
        lcao: 3_u8,
        mass: 63.5460014343,
        potential: "Cu_00PBE.usp",
        spin: 1_u8,
        covalent_radius: Some(1.12),
    },
    Element {
        symbol: ElementSymbol::Zn,
        atomic_number: 30_u8,
        lcao: 4_u8,
        mass: 65.3799972534,
        potential: "Zn_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.18),
    },
    Element {
        symbol: ElementSymbol::Ga,
        atomic_number: 31_u8,
        lcao: 4_u8,
        mass: 69.7350006104,
        potential: "Ga_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.24),
    },
    Element {
        symbol: ElementSymbol::Ge,
        atomic_number: 32_u8,
        lcao: 3_u8,
        mass: 72.5899963379,
        potential: "Ge_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.21),
    },
    Element {
        symbol: ElementSymbol::As,
        atomic_number: 33_u8,
        lcao: 3_u8,
        mass: 74.9219970703,
        potential: "As_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.21),
    },
    Element {
        symbol: ElementSymbol::Se,
        atomic_number: 34_u8,
        lcao: 3_u8,
        mass: 78.9599990845,
        potential: "Se_00.usp",
        spin: 0_u8,
        covalent_radius: Some(1.16),
    },
    Element {
        symbol: ElementSymbol::Br,
        atomic_number: 35_u8,
        lcao: 3_u8,
        mass: 79.9039993286,
        potential: "Br_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.14),
    },
    Element {
        symbol: ElementSymbol::Kr,
        atomic_number: 36_u8,
        lcao: 3_u8,
        mass: 83.8000030518,
        potential: "Kr_00.usp",
        spin: 0_u8,
        covalent_radius: Some(1.17),
    },
    Element {
        symbol: ElementSymbol::Rb,
        atomic_number: 37_u8,
        lcao: 4_u8,
        mass: 85.4680023193,
        potential: "Rb_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(2.1),
    },
    Element {
        symbol: ElementSymbol::Sr,
        atomic_number: 38_u8,
        lcao: 4_u8,
        mass: 87.6200027466,
        potential: "Sr_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.85),
    },
    Element {
        symbol: ElementSymbol::Y,
        atomic_number: 39_u8,
        lcao: 3_u8,
        mass: 88.90599823,
        potential: "Y_00PBE.uspcc",
        spin: 0_u8,
        covalent_radius: Some(1.63),
    },
    Element {
        symbol: ElementSymbol::Zr,
        atomic_number: 40_u8,
        lcao: 5_u8,
        mass: 91.2200012207,
        potential: "Zr_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.54),
    },
    Element {
        symbol: ElementSymbol::Nb,
        atomic_number: 41_u8,
        lcao: 5_u8,
        mass: 92.90599823,
        potential: "Nb_00PBE.usp",
        spin: 1_u8,
        covalent_radius: Some(1.47),
    },
    Element {
        symbol: ElementSymbol::Mo,
        atomic_number: 42_u8,
        lcao: 5_u8,
        mass: 95.9400024414,
        potential: "Mo_00PBE.usp",
        spin: 2_u8,
        covalent_radius: Some(1.38),
    },
    Element {
        symbol: ElementSymbol::Tc,
        atomic_number: 43_u8,
        lcao: 5_u8,
        mass: 98.90599823,
        potential: "Tc_00PBE.usp",
        spin: 3_u8,
        covalent_radius: Some(1.28),
    },
    Element {
        symbol: ElementSymbol::Ru,
        atomic_number: 44_u8,
        lcao: 5_u8,
        mass: 101.0699996948,
        potential: "Ru_00PBE.usp",
        spin: 5_u8,
        covalent_radius: Some(1.25),
    },
    Element {
        symbol: ElementSymbol::Rh,
        atomic_number: 45_u8,
        lcao: 3_u8,
        mass: 102.90599823,
        potential: "Rh_00PBE.usp",
        spin: 4_u8,
        covalent_radius: Some(1.25),
    },
    Element {
        symbol: ElementSymbol::Pd,
        atomic_number: 46_u8,
        lcao: 3_u8,
        mass: 106.4000015259,
        potential: "Pd_00PBE.usp",
        spin: 2_u8,
        covalent_radius: Some(1.2),
    },
    Element {
        symbol: ElementSymbol::Ag,
        atomic_number: 47_u8,
        lcao: 3_u8,
        mass: 107.8679962158,
        potential: "Ag_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.28),
    },
    Element {
        symbol: ElementSymbol::Cd,
        atomic_number: 48_u8,
        lcao: 4_u8,
        mass: 112.4100036621,
        potential: "Cd_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.36),
    },
    Element {
        symbol: ElementSymbol::In,
        atomic_number: 49_u8,
        lcao: 4_u8,
        mass: 114.8199996948,
        potential: "In_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.42),
    },
    Element {
        symbol: ElementSymbol::Sn,
        atomic_number: 50_u8,
        lcao: 3_u8,
        mass: 118.6900024414,
        potential: "Sn_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.4),
    },
    Element {
        symbol: ElementSymbol::Sb,
        atomic_number: 51_u8,
        lcao: 3_u8,
        mass: 121.75,
        potential: "Sb_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.4),
    },
    Element {
        symbol: ElementSymbol::Te,
        atomic_number: 52_u8,
        lcao: 3_u8,
        mass: 127.5999984741,
        potential: "Te_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.36),
    },
    Element {
        symbol: ElementSymbol::I,
        atomic_number: 53_u8,
        lcao: 3_u8,
        mass: 126.9039993286,
        potential: "I_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.33),
    },
    Element {
        symbol: ElementSymbol::Xe,
        atomic_number: 54_u8,
        lcao: 3_u8,
        mass: 131.3000030518,
        potential: "Xe_00.usp",
        spin: 0_u8,
        covalent_radius: Some(1.31),
    },
    Element {
        symbol: ElementSymbol::Cs,
        atomic_number: 55_u8,
        lcao: 4_u8,
        mass: 132.9049987793,
        potential: "Cs_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(2.32),
    },
    Element {
        symbol: ElementSymbol::Ba,
        atomic_number: 56_u8,
        lcao: 4_u8,
        mass: 137.3300018311,
        potential: "Ba_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.96),
    },
    Element {
        symbol: ElementSymbol::La,
        atomic_number: 57_u8,
        lcao: 6_u8,
        mass: 138.9049987793,
        potential: "La_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.8),
    },
    Element {
        symbol: ElementSymbol::Ce,
        atomic_number: 58_u8,
        lcao: 6_u8,
        mass: 140.1199951172,
        potential: "Ce_00PBE.usp",
        spin: 1_u8,
        covalent_radius: Some(1.63),
    },
    Element {
        symbol: ElementSymbol::Pr,
        atomic_number: 59_u8,
        lcao: 6_u8,
        mass: 140.9080047607,
        potential: "Pr_00.usp",
        spin: 2_u8,
        covalent_radius: Some(1.76),
    },
    Element {
        symbol: ElementSymbol::Nd,
        atomic_number: 60_u8,
        lcao: 6_u8,
        mass: 144.2400054932,
        potential: "Nd_00.usp",
        spin: 3_u8,
        covalent_radius: Some(1.74),
    },
    Element {
        symbol: ElementSymbol::Pm,
        atomic_number: 61_u8,
        lcao: 6_u8,
        mass: 147.0,
        potential: "Pm_00.usp",
        spin: 4_u8,
        covalent_radius: Some(1.73),
    },
    Element {
        symbol: ElementSymbol::Sm,
        atomic_number: 62_u8,
        lcao: 6_u8,
        mass: 150.3999938965,
        potential: "Sm_00.usp",
        spin: 5_u8,
        covalent_radius: Some(1.72),
    },
    Element {
        symbol: ElementSymbol::Eu,
        atomic_number: 63_u8,
        lcao: 6_u8,
        mass: 151.9600067139,
        potential: "Eu_00.usp",
        spin: 6_u8,
        covalent_radius: Some(1.68),
    },
    Element {
        symbol: ElementSymbol::Gd,
        atomic_number: 64_u8,
        lcao: 6_u8,
        mass: 157.25,
        potential: "Gd_00.usp",
        spin: 7_u8,
        covalent_radius: Some(1.69),
    },
    Element {
        symbol: ElementSymbol::Tb,
        atomic_number: 65_u8,
        lcao: 6_u8,
        mass: 158.9250030518,
        potential: "Tb_00.usp",
        spin: 6_u8,
        covalent_radius: Some(1.68),
    },
    Element {
        symbol: ElementSymbol::Dy,
        atomic_number: 66_u8,
        lcao: 6_u8,
        mass: 162.5,
        potential: "Dy_00.usp",
        spin: 5_u8,
        covalent_radius: Some(1.67),
    },
    Element {
        symbol: ElementSymbol::Ho,
        atomic_number: 67_u8,
        lcao: 6_u8,
        mass: 164.9299926758,
        potential: "Ho_00PBE.usp",
        spin: 4_u8,
        covalent_radius: Some(1.66),
    },
    Element {
        symbol: ElementSymbol::Er,
        atomic_number: 68_u8,
        lcao: 6_u8,
        mass: 167.2599945068,
        potential: "Er_00.usp",
        spin: 3_u8,
        covalent_radius: Some(1.65),
    },
    Element {
        symbol: ElementSymbol::Tm,
        atomic_number: 69_u8,
        lcao: 6_u8,
        mass: 168.9340057373,
        potential: "Tm_00.usp",
        spin: 2_u8,
        covalent_radius: Some(1.64),
    },
    Element {
        symbol: ElementSymbol::Yb,
        atomic_number: 70_u8,
        lcao: 6_u8,
        mass: 173.0399932861,
        potential: "Yb_00PBE.usp",
        spin: 1_u8,
        covalent_radius: Some(1.7),
    },
    Element {
        symbol: ElementSymbol::Lu,
        atomic_number: 71_u8,
        lcao: 4_u8,
        mass: 174.9700012207,
        potential: "Lu_00.usp",
        spin: 0_u8,
        covalent_radius: Some(1.62),
    },
    Element {
        symbol: ElementSymbol::Hf,
        atomic_number: 72_u8,
        lcao: 3_u8,
        mass: 178.4900054932,
        potential: "Hf_00PBE.uspcc",
        spin: 0_u8,
        covalent_radius: Some(1.52),
    },
    Element {
        symbol: ElementSymbol::Ta,
        atomic_number: 73_u8,
        lcao: 3_u8,
        mass: 180.9479980469,
        potential: "Ta_00PBE.usp",
        spin: 1_u8,
        covalent_radius: Some(1.46),
    },
    Element {
        symbol: ElementSymbol::W,
        atomic_number: 74_u8,
        lcao: 5_u8,
        mass: 183.8500061035,
        potential: "W_00PBE.usp",
        spin: 2_u8,
        covalent_radius: Some(1.37),
    },
    Element {
        symbol: ElementSymbol::Re,
        atomic_number: 75_u8,
        lcao: 5_u8,
        mass: 186.2070007324,
        potential: "Re_00PBE.usp",
        spin: 3_u8,
        covalent_radius: Some(1.31),
    },
    Element {
        symbol: ElementSymbol::Os,
        atomic_number: 76_u8,
        lcao: 5_u8,
        mass: 190.1999969482,
        potential: "Os_00PBE.usp",
        spin: 5_u8,
        covalent_radius: Some(1.29),
    },
    Element {
        symbol: ElementSymbol::Ir,
        atomic_number: 77_u8,
        lcao: 3_u8,
        mass: 192.2200012207,
        potential: "Ir_00PBE.usp",
        spin: 4_u8,
        covalent_radius: Some(1.22),
    },
    Element {
        symbol: ElementSymbol::Pt,
        atomic_number: 78_u8,
        lcao: 3_u8,
        mass: 195.0899963379,
        potential: "Pt_00PBE.usp",
        spin: 4_u8,
        covalent_radius: Some(1.23),
    },
    Element {
        symbol: ElementSymbol::Au,
        atomic_number: 79_u8,
        lcao: 3_u8,
        mass: 196.966003418,
        potential: "Au_00PBE.usp",
        spin: 2_u8,
        covalent_radius: Some(1.24),
    },
    Element {
        symbol: ElementSymbol::Hg,
        atomic_number: 80_u8,
        lcao: 4_u8,
        mass: 200.5899963379,
        potential: "Hg_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.33),
    },
    Element {
        symbol: ElementSymbol::Tl,
        atomic_number: 81_u8,
        lcao: 4_u8,
        mass: 204.3699951172,
        potential: "Tl_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.44),
    },
    Element {
        symbol: ElementSymbol::Pb,
        atomic_number: 82_u8,
        lcao: 4_u8,
        mass: 207.1999969482,
        potential: "Pb_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.44),
    },
    Element {
        symbol: ElementSymbol::Bi,
        atomic_number: 83_u8,
        lcao: 3_u8,
        mass: 208.9799957275,
        potential: "Bi_00PBE.usp",
        spin: 0_u8,
        covalent_radius: Some(1.51),
    },
    Element {
        symbol: ElementSymbol::Po,
        atomic_number: 84_u8,
        lcao: 3_u8,
        mass: 209.0,
        potential: "Po_00.usp",
        spin: 0_u8,
        covalent_radius: Some(1.45),
    },
    Element {
        symbol: ElementSymbol::At,
        atomic_number: 85_u8,
        lcao: 3_u8,
        mass: 210.0,
        potential: "At_00.usp",
        spin: 0_u8,
        covalent_radius: Some(1.47),
    },
    Element {
        symbol: ElementSymbol::Rn,
        atomic_number: 86_u8,
        lcao: 3_u8,
        mass: 222.0,
        potential: "Rn_00.usp",
        spin: 0_u8,
        covalent_radius: Some(1.42),
    },
    Element {
        symbol: ElementSymbol::Fr,
        atomic_number: 87_u8,
        lcao: 4_u8,
        mass: 223.0,
        potential: "Fr_00.usp",
        spin: 0_u8,
        covalent_radius: None,
    },
    Element {
        symbol: ElementSymbol::Ra,
        atomic_number: 88_u8,
        lcao: 4_u8,
        mass: 226.0,
        potential: "Ra_00.usp",
        spin: 0_u8,
        covalent_radius: Some(2.01),
    },
    Element {
        symbol: ElementSymbol::Ac,
        atomic_number: 89_u8,
        lcao: 4_u8,
        mass: 227.0,
        potential: "Ac_00.recpot",
        spin: 0_u8,
        covalent_radius: Some(1.86),
    },
    Element {
        symbol: ElementSymbol::Th,
        atomic_number: 90_u8,
        lcao: 6_u8,
        mass: 232.0379943848,
        potential: "Th_00.usp",
        spin: 1_u8,
        covalent_radius: Some(1.75),
    },
    Element {
        symbol: ElementSymbol::Pa,
        atomic_number: 91_u8,
        lcao: 6_u8,
        mass: 231.0,
        potential: "Pa_00.usp",
        spin: 2_u8,
        covalent_radius: Some(1.69),
    },
    Element {
        symbol: ElementSymbol::U,
        atomic_number: 92_u8,
        lcao: 6_u8,
        mass: 238.029006958,
        potential: "U_00PBE.usp",
        spin: 3_u8,
        covalent_radius: Some(1.7),
    },
    Element {
        symbol: ElementSymbol::Np,
        atomic_number: 93_u8,
        lcao: 6_u8,
        mass: 237.0,
        potential: "Np_00.usp",
        spin: 4_u8,
        covalent_radius: Some(1.71),
    },
    Element {
        symbol: ElementSymbol::Pu,
        atomic_number: 94_u8,
        lcao: 6_u8,
        mass: 244.0,
        potential: "Pu_00PBE.usp",
        spin: 5_u8,
        covalent_radius: Some(1.72),
    },
    Element {
        symbol: ElementSymbol::Am,
        atomic_number: 95_u8,
        lcao: 6_u8,
        mass: 243.0,
        potential: "Am_00.usp",
        spin: 6_u8,
        covalent_radius: Some(1.66),
    },
    Element {
        symbol: ElementSymbol::Cm,
        atomic_number: 96_u8,
        lcao: 6_u8,
        mass: 247.0,
        potential: "Cm_00PBE.usp",
        spin: 7_u8,
        covalent_radius: Some(1.66),
    },
    Element {
        symbol: ElementSymbol::Bk,
        atomic_number: 97_u8,
        lcao: 6_u8,
        mass: 247.0,
        potential: "Bk_00.usp",
        spin: 6_u8,
        covalent_radius: None,
    },
    Element {
        symbol: ElementSymbol::Cf,
        atomic_number: 98_u8,
        lcao: 6_u8,
        mass: 251.0,
        potential: "Cf_00.usp",
        spin: 5_u8,
        covalent_radius: None,
    },
    Element {
        symbol: ElementSymbol::Es,
        atomic_number: 99_u8,
        lcao: 6_u8,
        mass: 252.0,
        potential: "Es_00.usp",
        spin: 4_u8,
        covalent_radius: None,
    },
    Element {
        symbol: ElementSymbol::Fm,
        atomic_number: 100_u8,
        lcao: 6_u8,
        mass: 257.0,
        potential: "Fm_00.usp",
        spin: 3_u8,
        covalent_radius: None,
    },
    Element {
        symbol: ElementSymbol::Md,
        atomic_number: 101_u8,
        lcao: 6_u8,
        mass: 258.0,
        potential: "Md_00.usp",
        spin: 2_u8,
        covalent_radius: None,
    },
    Element {
        symbol: ElementSymbol::No,
        atomic_number: 102_u8,
        lcao: 6_u8,
        mass: 259.0,
        potential: "No_00.usp",
        spin: 1_u8,
        covalent_radius: None,
    },
    Element {
        symbol: ElementSymbol::Lr,
        atomic_number: 103_u8,
        lcao: 5_u8,
        mass: 262.0,
        potential: "Lr_00.usp",
        spin: 0_u8,
        covalent_radius: None,
    },
];
